# Generated by Django 3.2 on 2022-06-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_favoriteschatrooms_favoritescomments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteschatrooms',
            options={'verbose_name_plural': 'Favorites Chatrooms'},
        ),
        migrations.AlterModelOptions(
            name='favoritescomments',
            options={'verbose_name_plural': 'Favorites Comments'},
        ),
    ]
